---
title: ''
editor:
  render-on-save: true
format:
  pdf:
    documentclass: exam
    papersize: letter
    fontsize: 10pt
    include-in-header:
      - ./my-header.tex
      - ./my-macros.tex
    toc: false
    number-sections: true
    colorlinks: false
---


\noindent\makebox[0.75\textwidth]{Name:\enspace\hrulefill}

\vspace{5mm}

\begin{center}
    \LARGE{\textbf{In-class final, EC421}}
    \\ \large{180 points possible}
\end{center}

\vspace{5mm}

```{r, setup, include=FALSE}
# Packages
library(pacman)
p_load(fastverse, extrafont, latex2exp, ggplot2, scales)
```

## True or false (105 points; 35 questions)

\textbf{Note:} In this section, select the correct answer (true or false). You do not need to explain your answer.

\begin{questions}

\tf Even if an estimator is biased, it can still be consistent.

\tf The variable $x_t = 0.3 t + \varepsilon_{t}$ is stationary (assume $\varepsilon_{t}$ is mean zero).

\tf Exogeneity requires that the regressors are entirely unrelated to the disturbance.

\tf Measurement error in an explanatory variable tends to bias OLS's coefficient estimates toward zero.

\tf The instrumental variable (IV) estimator requires that the regressor of interest is exogenous.

\tf When disturbances' means differ across groups, we have heteroskedasticity.

\tf In the Neyman-Rubin framework, $\text{Avg}(y_{1} | D_{i} = 0)$ represents the average untreated outcome for the treated group.

\tf Adding additional variables does not always increase R$^2$.

\tf For the model
$$
  \text{Health}_t = \beta_0 + \beta_1 \text{Income}_t + \beta_2 \text{Income}_{t-1} + \beta_3 \text{Income}_{t-2} + u_t
$$
income's total effect of income on health is $\beta_1 + \beta_2 + \beta_3$.

\tf Heteroskedastic disturbances make OLS biased for estimating coefficients.

\tf The presence of omitted-variable bias implies that OLS is also inconsistent.

\tf By including a lagged dependent variable, we implicitly include lags of explanatory variables.

\tf If the disturbance is heteroskedastic, the usual $t$ and $F$ tests are not valid.

\tf If we estimate the econometric model below via regression, $\hat{\beta}_1$ will equal \\ $\text{Avg(Health | College Graduate)} - \text{Avg(Health | Non-Graduate)}$.
\begin{equation*}
  \text{Health}_i = \beta_0 + \beta_1 \text{(College Graduate)}_i + u_i
\end{equation*}

\tf Exogeneity essentially says that the disturbance must be independent of your explanatory variables.

\tf OLS is biased when estimating coefficients in models with lagged outcome variables.

\tf The first stage of two-stage least squares (2SLS) involves regressing the outcome variable on the instrumental variable.

\tf If OLS is biased for estimating $\beta_1$ below, then it is also inconsistent for estimating $\beta_1$.
$$
  y_t = \beta_0 + \beta_1 x_t + \beta_2 x_{t-1} + u_t
$$

\tf A \textit{p}-value of 0.999 suggests the data do not support the null hypothesis.

\tf Random walks are non-stationary.

\tf In the Rubin causal model, $y_{1i}$ refers to the outcome for individual $i$ when it does not receive treatment.

\tf If $u_i$ correlates with $u_j$, then exogeneity is violated.

\tf If a Goldfeld-Quandt test finds that SSE$_1$ equals SSE$_2$, then it will conclude that there is statistically significant evidence of heteroskedasticity.

\tf In the model $\text{Births}_t = \beta_0 + \beta_1 \text{Income}_t + u_t$, the parameter $\beta_1$ gives the effect of income in the previous time period on births in the current period.

\tf Dynamic models with lagged outcome variables always violate contemporaneous exogeneity.

\tf The fundamental problem of causal inference is that a comparison of the treatment group to the control group tends to be biased by selection bias.

\tf The econometric model below allows the effect of gender on education to depend upon the individual's age.
\begin{equation*}
  \text{Education}_i = \beta_0 + \beta_1 \text{Female}_i + \beta_2 \text{Age}_i + \beta_3 \text{Female}_i \times \text{Age}_i + u_i
\end{equation*}

\tf Correlated disturbances make OLS biased when estimating standard errors.

\tf Randomizing the explanatory variable helps avoid selection bias.

\tf A variable will cause omitted-variable bias in OLS estimates for coefficients when the following things are true: 
\begin{enumerate}
    \item A variable is omitted from the regression.
    \item The omitted variable correlates with one of the included regressors.
\end{enumerate}

\tf The outcome $y_1$ is unobserved in the control group.

\tf In the model below, if the disturbance is \textit{not} autocorrelated, then OLS consistently estimates the coefficients.
$$y_{t} = \beta_0 + \beta_1 x_{t} + \beta_2 x_{t-1} + \beta_3 y_{t-1} + u_t$$

\tf In the model
$$\log \text{Quantity}_t = \beta_0 + \beta_1 \log \text{Price}_t + u_t$$
if $\hat{\beta}_1 = -0.9$, then, on average, a one-percent increase in price generates a 0.9-percent reduction in quantity (all else equal).

\tf If $\text{Var}(u_t) = 13 + 4 t$, then $u_t$ is variance stationary.

\tf If the variable $x_t$ is a random walk, then $x_t - x_{t-1}$ is nonstationary.

\end{questions}

## Short answer (75 points; 16 questions)

\textbf{Note:} In this section, briefly answer the questions/prompts in 1--3 short (and complete) sentences. We will deduct points for excessively long answers.

\begin{questions}

\setcounter{question}{35}

\question{} Suppose you estimate the following model with OLS
\begin{equation*}
  \text{Income}_i = \beta_0 + \beta_1 \text{Education}_i + \beta_2 \text{Female}_i + \beta_3 \text{Education}_i \times \text{Female}_i + u_i
\end{equation*}
and find parameter estimates $\hat{\beta}_0 = 30$, $\hat{\beta}_1 = 1$, $\hat{\beta}_2 = -5$, and $\hat{\beta}_3 = 0.5$.

\begin{parts}
  \part{(5 points)} Interpret $\hat{\beta}_3$ in the context of the model. \vspace{\stretch{1}}
  \part{(5 points)} What is the expected income for a non-female individual with 12 years of education? \vspace{\stretch{1}}
  \part{(5 points)} Explain how the regression above estimates two lines---and provide the slope of each line.  \vspace{\stretch{1}}
  \part{(5 points)} Explain how you could use this model to test for gender-based discrimination.  \vspace{\stretch{1}}
\end{parts}

\newpage

\question{} People commonly debate the impact of the minimum wage on unemployment. Suppose you have data on unemployment and minimum wage for 100 cities in the United States.

\begin{parts}
  \part{(3 points)} Write down the econometric (regression) model you would use to estimate the effect of minimum wage on unemployment. \vspace{\stretch{.8}}
  \part{(2 points)} Which parameter in your model gives the effect of minimum wage on unemployment? \vspace{\stretch{.8}}
  \part{(5 points)} Suppose you estimate your model (in (a) above) with OLS. Will these OLS estimates provide causal evidence about the effect of minimum wage on unemployment? Explain your answer. \vspace{\stretch{1}}
  \part{(5 points)} Could instrumental variables help here? Explain. \vspace{\stretch{1}}
\end{parts}

\newpage

\short Define the concept of a \textit{standard error}.

\vspace{\stretch{1}}

\short Using mathematical notation, explain the concept of \textit{exogeneity}. Then explain why exogeneity is important for OLS.

\vspace{\stretch{1}}

\short Suppose you are analyzing time-series data for your job. Why should you be concerned about non-stationarity?

\vspace{\stretch{1}}

\newpage

\short The probability limit of the instrumental variables (IV) estimator (with instrument $z$, endogenous regressor $x$, and disturbance $u$) is
$$
  \text{plim} \; \hat{\beta}_{\text{IV}} = \beta + \dfrac{\text{Cov}(z, u)}{\text{Cov}(z, x)}
$$
Use the equation above to explain how a valid instrument makes the IV estimator consistent.

\vspace{\stretch{1}}

\short Explain how correlated disturbances can affect OLS.

\vspace{\stretch{1}}

\short Explain how randomized experiments avoid omitted-variable bias.

\vspace{\stretch{1}}

\newpage

\short Suppose you want to know how a recent advertising campaign affected sales. You have monthly data on sales (in dollars) and advertising spending (in dollars) for several years. Write down the econometric model you would use to estimate the effect of advertising on sales.

\vspace{\stretch{1}}

\short What are the key assumptions required to interpret your coefficient estimates from the model in the previous question as causal? Are these assumptions plausible in this context? Explain.

\vspace{\stretch{1}}


\end{questions}